"use strict";$(document).on("click",".event-button",function(event){event.preventDefault(),$("html, body").animate({scrollTop:$($.attr(this,"href")).offset().top},1e3),toggleHeader()});// 배너 & playing - 중복 처리
var star,genre,prototypeInfo={displayName:function displayName(data,item){item.dataset.list||(// playingInfo
item.querySelector(".name").textContent=data.name)},selectImage:function selectImage(data,item){var path;path=item.dataset.list?"../assets/images/".concat(data.poster,".jpg"):"../assets/images/".concat(data.image,".gif"),item.querySelector(".image").setAttribute("src",path),item.querySelector(".image").setAttribute("alt",data.name)},selectStar:function selectStar(data,item){var star=[],fillStar=Math.floor(data.star),emptyStar=Math.ceil(data.star-Math.floor(data.star));star="\u2605".repeat(fillStar)+"\u2606".repeat(emptyStar)+"(",item.querySelector(".icon").textContent=star},selectGenre:function selectGenre(data,item){var keys=Object.keys(data.genre);genre=keys.map(function(key){return data.genre[key]?key:""},data).filter(function(item){return""!=item}).join(", "),item.querySelector(".genre > dd").textContent=genre},clone:function clone(data){var item=this.origin.cloneNode(!0);item.setAttribute("data-origin",!1),item.querySelector(".review > p").textContent=data.review,item.querySelector(".review > cite").textContent=data.reviewUser,item.querySelector(".desc-title").textContent=data.name,item.querySelector(".rating").setAttribute("aria-label",data.star+"\uC810"),item.querySelector(".rating").textContent=data.star,item.querySelector(".actor > dd").textContent=data.actor,item.querySelector(".director > dd").textContent=data.director,this.displayName(data,item),this.selectImage(data,item),this.selectStar(data,item),this.selectGenre(data,item),this.container.appendChild(item)}};function infoFactory(section){var info=Object.create(prototypeInfo);return info.elem=document.querySelector(section),info.container=info.elem.querySelector("ol"),info.origin=info.elem.querySelector("li:first-of-type"),info;// 이걸로 30분 삽질
}function populateInfo(subject){var keys=Object.keys(state.movieList).slice(1);keys.forEach(function(key){subject.clone(state.movieList[key])})}var bannerInfo=infoFactory("#banner"),playingInfo=infoFactory("#playing");populateInfo(bannerInfo),populateInfo(playingInfo);// 배너 영화정보 활성/비활성
var bannerItems=document.querySelectorAll("#banner li");function showOrHideInfo(state,bannerItem,info){"show"===state&&(bannerItem.classList.add("active"),info.classList.remove("hidden")),"hide"===state&&(bannerItem.classList.remove("active"),info.classList.add("hidden"))}function translateInfo(bannerItem,info){var coords={};-1==navigator.userAgent.indexOf("Chrome")?(coords.left=banner.offsetLeft-1.5*bannerItem.offsetWidth,coords.top=bannerItem.offsetTop+banner.offsetTop):(coords.left=banner.offsetLeft,coords.top=bannerItem.offsetTop+banner.offsetTop+.5*banner.offsetHeight),info.style.transform="translate(".concat(coords.left,"px, ").concat(coords.top,"px)")}function handleMouseEnter(){if(!(window.innerWidth<screen.desktop)){var info=this.querySelector(".info");translateInfo(this,info),showOrHideInfo("show",this,info)}}function handleMouseLeave(){if(!(window.innerWidth<screen.desktop)){var info=this.querySelector(".info");showOrHideInfo("hide",this,info)}}bannerItems.forEach(function(item){item.addEventListener("mouseenter",handleMouseEnter),item.addEventListener("mouseleave",handleMouseLeave)});// New 리사이즈 이벤트
var firstReview=document.querySelector("#new .review > p:first-of-type");function handleReview(){window.innerWidth>screen.tablet?firstReview.classList.remove("hidden"):firstReview.classList.add("hidden")}window.addEventListener("DOMContentLoaded",handleReview),window.addEventListener("resize",handleReview);// Playing 이미지카드 클릭 이벤트
var imageCards=document.querySelectorAll(".image-card");function flipCard(){window.innerWidth<screen.tablet&&this.classList.toggle("flipped")}imageCards.forEach(function(card){return card.addEventListener("click",flipCard)});// Playing 높이 조절 이벤트
function isChangableHeight(){var playing=document.querySelector("#playing"),imagesCards=playing.querySelectorAll(".image-card");imagesCards.forEach(function(card){var image=card.querySelector(".image"),height=image.clientHeight;card.style.setProperty("--imageHeight","".concat(height,"px"))})}// load 이벤트를 사용하는 이유
// - isChangableHeight()는 이미지의 clientHeight를 이용하는 함수
// - img태그를 인식하고 바로 넘겨버리는 DOMContentLoaded는 적합하지 않음
window.addEventListener("load",isChangableHeight),window.addEventListener("resize",isChangableHeight);// 로컬스토리지 데이터 저장
function saveData(){var data={},userId=window.location.search.split("=")[1];userId&&(data.id=userId,localStorage.setItem("bookedData",JSON.stringify(data)))}saveData();